config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :customers
  resources :sales, :except => [:show, :edit, :update]
  get '/products', to: 'products#index'
  get '/sectors', to: 'sectors#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  company    :string
#  email      :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  sector_id  :integer
#

class Customer < ActiveRecord::Base
  belongs_to :sector
  has_many :sales
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id          :integer          not null, primary key
#  date        :date
#  quantity    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  customer_id :integer
#  product_id  :integer
#

class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
  after_save :discount_quantity

  def verify_stock
    self.quantity > self.product.quantity ? false : true
  end

  def discount_quantity
    self.product.update(quantity: self.product.quantity - self.quantity)
  end

end

app/models/sector.rb
# == Schema Information
#
# Table name: sectors
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sector < ActiveRecord::Base
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path, notice: "El cliente fue creado con éxito"
    else
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path, notice: "La información del cliente ha sido actualizada"
    else
      render :edit
    end
  end

  def destroy
    customer = Customer.find(params[:id])
    customer.destroy

    redirect_to customers_path, notice: "El cliente fue eliminado con éxito"
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :company, :email, :phone, :sector_id)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    if @sale.verify_stock
      if @sale.save
        redirect_to sales_path, notice: "Se ha creado la venta con éxito"
      else
        render :new
      end
    else
      @sale.errors.add(:quantity, "No hay existencias suficientes")
      render :new, notice: "No hay esa cantidad en Stock"
    end
  end

  def destroy
    sale = Sale.find(params[:id])
    sale.destroy

    redirect_to sales_path, notice: "Has eliminado la venta satisfactoriamente"
  end

  private
   def sale_params
     params.require(:sale).permit(:date, :quantity, :product_id, :customer_id)
   end

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  def index
    @sectors = Sector.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  def form_title
    @customer.new_record? ? "Registrar Cliente" : "Actualizar cliente"
  end
end

app/views/customers/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <h1><%= form_title %></h1><br><br>

      <%= form_for @customer do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del cliente" %>
        </div>
        <div class="form-group">
          <%= f.text_field :company, class: "form-control input-lg", placeholder: "Ingresa el nombre de la empresa" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control input-lg", placeholder: "Ingresa el e-mail" %>
        </div>
        <div class="form-group">
          <%= f.text_field :phone, class: "form-control input-lg", placeholder: "Ingresa el número de teléfono" %>
        </div>
        <div class="form-group">
          <div class="field form-group">
            <%= f.collection_select(:sector_id, Sector.all, :id, :name,{ prompt:"Sector" }, { class: "form-control input-lg"}) %>
          </div>
        </div>
        <div>
          <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Clientes</h1>
      <div class="text-right">
        <%= link_to "Registrar Cliente", new_customer_path, class: "btn btn-primary" %>
      </div>

      <table class="table">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Empresa</th>
          <th>E-mail</th>
          <th>Teléfono</th>
          <th>Sector Ecónomico</th>
          <th></th>
        </tr>
        <% @customers.each do |c| %>
          <tr>
            <td><%= c.id %></td>
            <td><%=link_to c.name, c %></td>
            <td><%= c.company %></td>
            <td><%= c.email %></td>
            <td><%= c.phone %></td>
            <td><%= c.sector.name %></td>
            <td>
              <%= link_to "Actualizar", edit_customer_path(c) %>
              <%= link_to "Eliminar",  c, method: :delete, data: { confirm: "Estas seguro que deseas eliminar este cliente?" }%>
            </td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Registrar Cliente</h1>
      <%= form_for @customer do |f| %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Ingresa el nombre del cliente" %>
        </div>
        <div class="form-group">
          <%= f.text_field :company, class: "form-control input-lg", placeholder: "Ingresa el nombre de la empresa" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control input-lg", placeholder: "Ingresa el e-mail" %>
        </div>
        <div class="form-group">
          <%= f.text_field :phone, class: "form-control input-lg", placeholder: "Ingresa el número" %>
        </div>
        <div>
          <%= f.submit "Registrar cliente", class: "btn btn-primary btn-lg btn-block" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">
      <h3>Nombre: <%= @customer.name %></h1>
      <p>Empresa: <%= @customer.company %></p>
      <p>E-mail: <%= @customer.email %></p>
      <p>Teléfono: <%= @customer.phone %></p>
      <p>Sector Ecónomico: <%= @customer.sector.name %></p>
      <br><br>

      <% if @customer.sales != []%>
        <h3>Productos Comprados</h3>
        <table class="table">
          <tr>
            <th>Fecha</th>
            <th>Producto</th>
            <th>Cantidad</th>
          </tr>
          <% @customer.sales.each do |s| %>
            <tr>
              <td><%= s.date %></td>
              <td><%= s.product.name %></td>
              <td><%= s.quantity %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>Este cliente aún no registra compras</p>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andamios</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
     <div class="container-fluid">
       <div class="navbar-header">
         <a class="navbar-brand">Andamios Del Norte</a>
       </div>
       <ul class="nav navbar-nav navbar-right">
         <li><a href="<%= customers_path  %>">Clientes</a></li>
         <li><a href="<%= sales_path %>">Ventas</a></li>
         <li><a href="<%= products_path %>">Productos</a></li>
         <li><a href="<%= sectors_path %>">Sectores</a></li>
       </ul>
     </div>
   </nav>

    <% if flash[:notice]%>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Productos</h1><br><br>

      <table class="table">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Cantidad</th>
        </tr>
        <% @products.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td><%= p.name %></td>
            <td><%= p.quantity %></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/sales/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Ventas</h1>
      <div class="text-right">
        <%= link_to "Registrar Venta", new_sale_path, class: "btn btn-primary" %>
      </div>

      <table class="table">
        <tr>
          <th>Id</th>
          <th>Fecha</th>
          <th>Producto</th>
          <th>Cantidad</th>
          <th>Cliente</th>
          <th></th>
        </tr>
        <% @sales.each do |s| %>
          <tr>
            <td><%= s.id %></td>
            <td><%= s.date %></td>
            <td><%= s.product.name%></td>
            <td><%= s.quantity %></td>
            <td><%= s.customer.name %></td>
            <td>
              <%= link_to "Eliminar",  s, method: :delete, data: { confirm: "Estas seguro que deseas eliminar esta venta?" }%>
            </td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">

      <% if @sale.errors.any? %>
       <div id="errors_explanation">
         <h2><%= pluralize(@sale.errors.count,"error") %> No se pudo guardar esta venta:</h2>
         <ul>
           <% @sale.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
         </ul>
       </div>
      <% end %>

      <h1>Nueva Venta</h1><br><br>
      <%= form_for @sale do |f| %>
        <div class="form-group">
          <%= f.text_field :date, class: "form-control input-lg", placeholder: "Ingresa la fecha de la compra" %>
        </div>
        <div class="form-group">
          <%= f.text_field :quantity, class: "form-control input-lg", placeholder: "Ingresa la cantidad" %>
        </div>
        <div class="form-group">
          <div class="field form-group">
            <%= f.collection_select(:product_id, Product.all, :id, :name, {prompt: "Producto"}, {class: "form-control input-lg"})%>
          </div>
        </div>
        <div class="form-group">
          <div class="field form-group">
            <%= f.collection_select(:customer_id, Customer.all, :id, :name, {prompt: "Cliente"}, {class: "form-control input-lg"})%>
          </div>
        </div>
        <div>
          <%= f.submit "Crear Venta", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/sales/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Fecha: <%= @sale.date %></h1>
      <p>Cantidad: <%= @sale.quantity %></p>
    </div>
  </div>
</div>

app/views/sectors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Sectores</h1><br><br>

      <table class="table">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
        </tr>
        <% @sectors.each do |s| %>
          <tr>
            <td><%= s.id %></td>
            <td><%= s.name %></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>